apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-db-5g
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  nfs:
    path: /export/racktables-db
    server: 192.168.111.226
  # rm -rf /thevolume/* db storage after deleting deployment
  # retain: keep the data around 
  persistentVolumeReclaimPolicy: Retain
